### ISSUE TITLE
Not compatible with http 1.0.0

### ISSUE THREAD

**Issue by zakblacki** [martin-braun-net/google_maps_place_picker_mb#56]
Please update 

> Because google_maps_place_picker_mb >=2.0.0-mb.22 depends on http ^0.13.5 and project depends on http ^1.0.0, google_maps_place_picker_mb >=2.0.0-mb.22 is forbidden.
> So, because project depends on google_maps_place_picker_mb ^3.0.2, version solving failed.

**Comment by martin-braun** [comment]
I tried to, but it's blocked by https://github.com/lejard-h/google_maps_webservice/issues/149

Don't really have the time to replace `google_maps_webservice`. Feel free to create a PR on https://github.com/martin-braun/google_maps_place_picker_mb/tree/dart-3.

**Comment by BobbyBakes** [comment]
Is this coming off hold anytime soon.  
There are a lot of packages now that depend on http 1.0 and above. I think there will end up being a lot of folks with dependency issues. 

I just hit one with the latest flutter 3.0 upgrades

**Comment by giorgio79** [comment]
Some peeps already updated google_maps_webservice. Just need to replace in pubspec with the latest at 
https://github.com/hectorhasap/google_maps_webservice

recommend cloning the repo first :)

```
  google_maps_webservice:
    git:
      url: https://github.com/hectorhasap/google_maps_webservice
      ref: main
      publish_to: none
```
